version: "3.2"

services:

  api:
    build:
      context: .
    image: nowyouseeme
    container_name: nowyouseeme-api
    env_file: docker-compose.env
    environment:
      SERVICES: api, authorization
      PORT: 3000
    depends_on:
      - nats
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    networks:
      - internal

  presence:
    build:
      context: .
    image: nowyouseeme
    container_name: nowyouseeme-presence
    env_file: docker-compose.env
    environment:
      SERVICES: presence
    labels:
      - "traefik.enable=false"
    depends_on:
      - nats
      - redis
    networks:
      - internal

  realtime:
    build:
      context: .
    image: nowyouseeme
    container_name: nowyouseeme-realtime
    env_file: docker-compose.env
    environment:
      SERVICES: realtime
    labels:
      - "traefik.enable=false"
    depends_on:
      - nats
      - redis
    networks:
      - internal

  nats:
    image: nats
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  redis:
    image: redis:alpine
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  traefik:
    image: traefik:1.7
    container_name: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.watch"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - internal
      - default

networks:
  internal:
